spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cinema?serverTimezone=CTT&characterEncoding=UTF-8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    max-active: 200
    max-idle: 20
    min-idle: 10
  resources:
    static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/, classpath:/static/html/
  thymeleaf:
    prefix: classpath:/static/html/
    cache: false
  jackson:
    time-zone: GMT+8

mybatis:
  mapper-locations: classpath:dataImpl/*/*Mapper.xml

