spring:
  datasource:
    url: jdbc:mysql://118.31.0.170:3306/oasis?serverTimezone=CTT&characterEncoding=UTF-8
    #url: jdbc:mysql://localhost:3306/oasisTest?serverTimezone=CTT&characterEncoding=UTF-8
    username: root
    password: Noname
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    tomcat:
      max-active: 20
      max-idle: 8
      min-idle: 8
      initial-size: 10

  jackson:
    time-zone: GMT+8
  resources:
    static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/, classpath:/static/html/
  thymeleaf:
    prefix: classpath:/static/html/
    cache: false
server:
  servlet:
    context-path: /

servlet:
  session:
    timeout: 7200

mybatis:
  mapper-locations: classpath:/dataIMP/*/*.xml
